#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

$commands = [
    new \KayStrobach\Releasy\Command\ReleaseCommand(),
    new \KayStrobach\Releasy\Command\ExtensionListCommand(),
    new \KayStrobach\Releasy\Command\PackageCommand(),
    new \KayStrobach\Releasy\Command\PharCommand(),
];

$application = new Application();
$application->addCommands($commands);

/** @var Command $defaultCommand */
$defaultCommand = $commands[0];
$application->setDefaultCommand($defaultCommand->getName());

$application->run();
