#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
}

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

$commands = [
    new \KayStrobach\Releasy\Command\Composer\SetVersionCommand(),
    new \KayStrobach\Releasy\Command\Git\TagCommand(),
    new \KayStrobach\Releasy\Command\Phar\CreateCommand(),
    new \KayStrobach\Releasy\Command\Release\CreateCommand(),
    new \KayStrobach\Releasy\Command\Release\UpdateChangelogCommand(),
    new \KayStrobach\Releasy\Command\TYPO3\Extension\ListCommand(),
    new \KayStrobach\Releasy\Command\TYPO3\Extension\PackageCommand(),
    new \KayStrobach\Releasy\Command\TYPO3\Extension\SetVersionCommand(),
];

$application = new Application('releasy', '1.0.0');
$application->addCommands($commands);

$application->setDefaultCommand('list');

$application->run();
